.TH backmiup-notification 1  "January, 2011" "Version 0.976" "USER COMMANDS"
.SH NAME
BackMiUp Notification \- Lightweight visual notification system for BackMiUp
.SH SYNOPSIS
.B backmeup-notification
[ \-a ]

.SH DESCRIPTION
This programm is a visible-notifications system which is only passively displaying backup statuses of Backmiup. Without options it only shows cron jobbed backups, but showing manual backups is also possible.
.SH OPTIONS
.TP
.B -a
Not only backup cron jobs are displayed, but manually made backups as well.
.SH AUTHOR
Rainer (backmiup@laryllian.de)
.br
I'm always happy about comments and suggestions.
.SH LICENSE
CC-GNU GPL Rainer
.SH SEE ALSO
backmiup(1)
.br
zenity(1)
